version: "3.3"
networks:
  backend:
services:
  db:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
  app:
    build: .
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB: postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      BUNDLE_GEMFILE: /app/Gemfile
    command: script/docker-entrypoint.sh
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - db
